
import type { Book, Author, Genre, CommunityPost, Pdf } from '@/lib/types';
import { PlaceHolderImages } from '@/lib/placeholder-images';

const getImage = (id: string) => {
  const image = PlaceHolderImages.find((img) => img.id === id);
  if (!image) {
    // Fallback to a default image if not found
    return { url: "https://picsum.photos/seed/default/400/600", hint: "image" };
  }
  return { url: image.imageUrl, hint: image.imageHint };
};

export const authors: Author[] = [
  { id: '1', name: 'Arundhati Roy' },
  { id: '2', name: 'Vikram Seth' },
  { id: '3', name: 'Amitav Ghosh' },
  { id: '4', name: 'Jhumpa Lahiri' },
  { id: '5', name: 'Frank Herbert' },
  { id: '6', name: 'Isaac Asimov' },
  { id: '7', name: 'George Orwell' },
  { id: '8', name: 'J.R.R. Tolkien' },
  { id: '9', name: 'Haruki Murakami' },
  { id: '10', name: 'Gabriel Garcia Marquez' },
  { id: '11', name: 'Jane Austen' },
  { id: '12', name: 'Agatha Christie' },
  { id: '13', name: 'Stephen King' },
  { id: '14', name: 'J.K. Rowling' },
  { id: '15', name: 'Walter Isaacson' },
  { id: '16', name: 'Yuval Noah Harari' },
  { id: '17', name: 'James Clear' },
  { id: '18', name: 'Brené Brown' },
  { id: '26', name: 'Morgan Housel' },
  { id: '27', name: 'Paulo Coelho' },
];

export const genres: Genre[] = [
  { id: '1', name: 'Fiction' },
  { id: '2', name: 'Non-Fiction' },
  { id: '3', name: 'Science Fiction' },
  { id: '4', name: 'Fantasy' },
  { id: '5', name: 'Mystery' },
  { id: '6', name: 'Biography' },
  { id: '7', name: 'Self-Help' },
  { id: '8', name: 'Thriller' },
  { id: '9', name: 'Finance' },
  { id: '10', name: 'History' },
];

export const books: Book[] = [
  {
    id: '1',
    title: 'The God of Small Things',
    author: authors[0],
    genre: genres[0],
    price: 399,
    rentalPrice: 99,
    coverImage: getImage('book-cover-5'),
    description: 'A story about the childhood experiences of fraternal twins whose lives are destroyed by the "Love Laws" that lay down "who should be loved, and how. And how much."',
    availability: 'in-stock',
  },
  {
    id: '2',
    title: 'A Suitable Boy',
    author: authors[1],
    genre: genres[0],
    price: 899,
    rentalPrice: 199,
    coverImage: getImage('book-cover-6'),
    description: 'Set in a newly independent India, the novel follows the story of four families over a period of 18 months, and centers on Mrs. Rupa Mehra\'s efforts to arrange the marriage of her younger daughter, Lata, to a "suitable boy".',
    availability: 'in-stock',
  },
  {
    id: '3',
    title: 'The Glass Palace',
    author: authors[2],
    genre: genres[1],
    price: 599,
    coverImage: getImage('book-cover-7'),
    description: 'The novel is set in Burma, Bengal, India, and Malaya, spans a century from the fall of the Konbaung Dynasty in Mandalay, to the modern era.',
    availability: 'out-of-stock',
  },
  {
    id: '4',
    title: 'The Namesake',
    author: authors[3],
    genre: genres[0],
    price: 450,
    rentalPrice: 120,
    coverImage: getImage('book-cover-8'),
    description: 'The novel examines the intricacies of immigrant life, the conflicts of assimilation, and the tangled ties between generations.',
    availability: 'in-stock',
  },
  {
    id: '5',
    title: 'Sea of Poppies',
    author: authors[2],
    genre: genres[0],
    price: 650,
    rentalPrice: 150,
    coverImage: getImage('new-book-13'),
    description: 'The first book of the Ibis trilogy, this novel is set in the first half of the 19th century, on the banks of the holy river Ganges, and on the ebb and tide of the Indian Ocean.',
    availability: 'in-stock',
  },
  {
    id: '6',
    title: 'The Ministry of Utmost Happiness',
    author: authors[0],
    genre: genres[0],
    price: 499,
    coverImage: getImage('new-book-14'),
    description: 'The novel weaves together the stories of people from different backgrounds in India, exploring themes of love, identity, and politics.',
    availability: 'out-of-stock',
  },
  {
    id: '7',
    title: 'Dune',
    author: authors[4],
    genre: genres[2],
    price: 799,
    rentalPrice: 180,
    coverImage: getImage('new-book-15'),
    description: 'A mythic and emotionally charged hero\'s journey, "Dune" tells the story of Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding.',
    availability: 'in-stock',
  },
  {
    id: '8',
    title: 'Foundation',
    author: authors[5],
    genre: genres[2],
    price: 550,
    rentalPrice: 130,
    coverImage: getImage('new-book-16'),
    description: 'For twelve thousand years the Galactic Empire has ruled supreme. Now it is dying. But only Hari Seldon, creator of the revolutionary science of psychohistory, can see into the future.',
    availability: 'in-stock',
  },
  {
    id: '9',
    title: 'Nineteen Eighty-Four',
    author: authors[6],
    genre: genres[2],
    price: 450,
    rentalPrice: 110,
    coverImage: getImage('new-book-1'),
    description: 'A dystopian novel set in Airstrip One, a province of the superstate Oceania in a world of perpetual war, omnipresent government surveillance, and public manipulation.',
    availability: 'in-stock',
  },
  {
    id: '10',
    title: 'The Hobbit',
    author: authors[7],
    genre: genres[3],
    price: 600,
    rentalPrice: 140,
    coverImage: getImage('new-book-2'),
    description: 'The enchanting prequel to The Lord of the Rings, The Hobbit is the story of Bilbo Baggins, a quiet and unassuming hobbit whose life is turned upside down when he joins a company of dwarves on a quest to reclaim their stolen treasure.',
    availability: 'in-stock',
  },
  {
    id: '11',
    title: 'Norwegian Wood',
    author: authors[8],
    genre: genres[0],
    price: 520,
    rentalPrice: 125,
    coverImage: getImage('new-book-3'),
    description: 'A nostalgic story of loss and burgeoning sexuality. It is told from the first-person perspective of Toru Watanabe, who looks back on his days as a college student living in Tokyo.',
    availability: 'in-stock',
  },
  {
    id: '12',
    title: 'One Hundred Years of Solitude',
    author: authors[9],
    genre: genres[0],
    price: 580,
    rentalPrice: 135,
    coverImage: getImage('new-book-4'),
    description: 'The story of the Buendía family, and chronicles the irreconcilable conflict between the demand for solitude and the need for love—in a tragicomedy of the human condition.',
    availability: 'out-of-stock',
  },
  {
    id: '13',
    title: 'Pride and Prejudice',
    author: authors[10],
    genre: genres[0],
    price: 350,
    rentalPrice: 90,
    coverImage: getImage('new-book-5'),
    description: 'A romantic novel of manners written by Jane Austen. The novel follows the character development of Elizabeth Bennet, the dynamic protagonist of the book.',
    availability: 'in-stock',
  },
  {
    id: '14',
    title: 'And Then There Were None',
    author: authors[11],
    genre: genres[4],
    price: 480,
    rentalPrice: 115,
    coverImage: getImage('new-book-6'),
    description: 'Ten strangers are lured to a remote island off the coast of Devon. Upon arrival, it is discovered that their host is mysteriously absent.',
    availability: 'in-stock',
  },
  {
    id: '15',
    title: 'The Shining',
    author: authors[12],
    genre: genres[7],
    price: 620,
    rentalPrice: 155,
    coverImage: getImage('new-book-7'),
    description: 'The story of Jack Torrance, an aspiring writer and recovering alcoholic who accepts a position as the off-season caretaker of the isolated historic Overlook Hotel in the Colorado Rockies.',
    availability: 'in-stock',
  },
  {
    id: '16',
    title: 'Harry Potter and the Sorcerer\'s Stone',
    author: authors[13],
    genre: genres[3],
    price: 650,
    rentalPrice: 160,
    coverImage: getImage('new-book-8'),
    description: 'The first novel in the Harry Potter series, it follows Harry Potter, a young wizard who discovers his magical heritage on his eleventh birthday, when he receives a letter of acceptance to Hogwarts School of Witchcraft and Wizardry.',
    availability: 'in-stock',
  },
  {
    id: '17',
    title: 'Steve Jobs',
    author: authors[14],
    genre: genres[5],
    price: 950,
    rentalPrice: 220,
    coverImage: getImage('new-book-9'),
    description: 'The authorized self-titled biography of Steve Jobs. The book was written at the request of Jobs by Walter Isaacson, a former executive at CNN and TIME.',
    availability: 'in-stock',
  },
  {
    id: '18',
    title: 'Sapiens: A Brief History of Humankind',
    author: authors[15],
    genre: genres[9],
    price: 750,
    rentalPrice: 180,
    coverImage: getImage('new-book-10'),
    description: 'A book by Yuval Noah Harari, first published in Hebrew in Israel in 2011 based on a series of lectures Harari taught at The Hebrew University of Jerusalem.',
    availability: 'in-stock',
  },
  {
    id: '19',
    title: 'Atomic Habits',
    author: authors[16],
    genre: genres[6],
    price: 700,
    rentalPrice: 170,
    coverImage: getImage('atomic-habits-cover'),
    description: 'An easy and proven way to build good habits and break bad ones. It offers a framework for improving every day.',
    availability: 'out-of-stock',
  },
  {
    id: '20',
    title: 'Daring Greatly',
    author: authors[17],
    genre: genres[6],
    price: 680,
    rentalPrice: 165,
    coverImage: getImage('new-book-12'),
    description: 'A book by Brené Brown that discusses the power of vulnerability, courage, worthiness, and shame.',
    availability: 'in-stock',
  },
  {
    id: '21',
    title: 'The Lord of the Rings',
    author: authors[7],
    genre: genres[3],
    price: 1200,
    rentalPrice: 250,
    coverImage: getImage('new-book-13'),
    description: 'An epic high-fantasy novel. The story began as a sequel to Tolkien\'s 1937 fantasy novel The Hobbit, but eventually developed into a much larger work.',
    availability: 'in-stock',
  },
  {
    id: '22',
    title: 'Kafka on the Shore',
    author: authors[8],
    genre: genres[0],
    price: 560,
    rentalPrice: 130,
    coverImage: getImage('new-book-14'),
    description: 'A 2002 novel by Japanese author Haruki Murakami. Its 2005 English translation was among "The 10 Best Books of 2005" from The New York Times.',
    availability: 'in-stock',
  },
  {
    id: '23',
    title: 'Love in the Time of Cholera',
    author: authors[9],
    genre: genres[0],
    price: 540,
    rentalPrice: 125,
    coverImage: getImage('new-book-15'),
    description: 'A novel that tells the story of Florentino Ariza and his love for Fermina Daza.',
    availability: 'in-stock',
  },
  {
    id: '24',
    title: 'Sense and Sensibility',
    author: authors[10],
    genre: genres[0],
    price: 380,
    rentalPrice: 95,
    coverImage: getImage('new-book-16'),
    description: 'A novel by Jane Austen, published in 1811. It was published anonymously; "By a Lady" appeared on the title page where the author\'s name might have been.',
    availability: 'out-of-stock',
  },
  {
    id: '25',
    title: 'Murder on the Orient Express',
    author: authors[11],
    genre: genres[4],
    price: 490,
    rentalPrice: 120,
    coverImage: getImage('new-book-17'),
    description: 'A detective novel by British writer Agatha Christie, featuring the Belgian detective Hercule Poirot.',
    availability: 'in-stock',
  },
  {
    id: '26',
    title: 'It',
    author: authors[12],
    genre: genres[7],
    price: 720,
    rentalPrice: 175,
    coverImage: getImage('new-book-18'),
    description: 'A 1986 horror novel by American author Stephen King. It was his 22nd book and his 17th novel written under his own name.',
    availability: 'in-stock',
  },
  {
    id: '27',
    title: 'Harry Potter and the Chamber of Secrets',
    author: authors[13],
    genre: genres[3],
    price: 670,
    rentalPrice: 165,
    coverImage: getImage('new-book-19'),
    description: 'The second novel in the Harry Potter series. The plot follows Harry\'s second year at Hogwarts School of Witchcraft and Wizardry.',
    availability: 'in-stock',
  },
  {
    id: '28',
    title: 'Leonardo da Vinci',
    author: authors[14],
    genre: genres[5],
    price: 1100,
    rentalPrice: 240,
    coverImage: getImage('new-book-20'),
    description: 'A biography of Leonardo da Vinci by Walter Isaacson. It is based on Leonardo\'s notebooks and new discoveries about his life and work.',
    availability: 'in-stock',
  },
  {
    id: '29',
    title: 'Homo Deus: A Brief History of Tomorrow',
    author: authors[15],
    genre: genres[1],
    price: 780,
    rentalPrice: 185,
    coverImage: getImage('new-book-21'),
    description: 'A book written by Israeli author Yuval Noah Harari, professor at the Hebrew University in Jerusalem. The book was first published in Hebrew in 2015.',
    availability: 'in-stock',
  },
  {
    id: '30',
    title: 'The Power of Habit',
    author: {id: '19', name: 'Charles Duhigg'},
    genre: genres[6],
    price: 710,
    rentalPrice: 170,
    coverImage: getImage('new-book-22'),
    description: 'A book by Charles Duhigg, a New York Times reporter, published in February 2012 by Random House.',
    availability: 'in-stock',
  },
  {
    id: '31',
    title: 'The Gifts of Imperfection',
    author: authors[17],
    genre: genres[6],
    price: 690,
    rentalPrice: 168,
    coverImage: getImage('new-book-23'),
    description: 'A New York Times bestseller by Brené Brown that has been helping readers to embrace a more authentic and wholehearted life.',
    availability: 'out-of-stock',
  },
  {
    id: '32',
    title: 'Animal Farm',
    author: authors[6],
    genre: genres[2],
    price: 320,
    rentalPrice: 80,
    coverImage: getImage('new-book-24'),
    description: 'An allegorical novella by George Orwell, first published in England on 17 August 1945.',
    availability: 'in-stock',
  },
  {
    id: '33',
    title: 'The Silmarillion',
    author: authors[7],
    genre: genres[3],
    price: 850,
    rentalPrice: 200,
    coverImage: getImage('new-book-25'),
    description: 'A collection of mythopoeic works by English writer J. R. R. Tolkien, edited and published posthumously by his son, Christopher Tolkien, in 1977.',
    availability: 'in-stock',
  },
  {
    id: '34',
    title: '1Q84',
    author: authors[8],
    genre: genres[0],
    price: 980,
    rentalPrice: 220,
    coverImage: getImage('new-book-26'),
    description: 'A dystopian novel written by Japanese writer Haruki Murakami, first published in three volumes in Japan in 2009–10.',
    availability: 'in-stock',
  },
  {
    id: '35',
    title: 'Chronicle of a Death Foretold',
    author: authors[9],
    genre: genres[0],
    price: 420,
    rentalPrice: 100,
    coverImage: getImage('new-book-27'),
    description: 'A novella by Gabriel García Márquez, published in 1981. It tells, in the form of a pseudo-journalistic reconstruction, the story of the murder of Santiago Nasar by the two Vicario brothers.',
    availability: 'in-stock',
  },
  {
    id: '36',
    title: 'Emma',
    author: authors[10],
    genre: genres[0],
    price: 400,
    rentalPrice: 100,
    coverImage: getImage('new-book-28'),
    description: 'A novel about youthful hubris and romantic misunderstandings, written by Jane Austen. It is set in the fictional country village of Highbury and the surrounding estates of Hartfield, Randalls and Donwell Abbey.',
    availability: 'in-stock',
  },
  {
    id: '37',
    title: 'The Murder of Roger Ackroyd',
    author: authors[11],
    genre: genres[4],
    price: 500,
    rentalPrice: 125,
    coverImage: getImage('new-book-29'),
    description: 'A work of detective fiction by British writer Agatha Christie, first published in June 1926 in the United Kingdom by William Collins, Sons.',
    availability: 'out-of-stock',
  },
  {
    id: '38',
    title: 'The Stand',
    author: authors[12],
    genre: genres[7],
    price: 880,
    rentalPrice: 210,
    coverImage: getImage('new-book-30'),
    description: 'A post-apocalyptic dark fantasy novel written by American author Stephen King and first published in 1978 by Doubleday.',
    availability: 'in-stock',
  },
  {
    id: '39',
    title: 'Harry Potter and the Prisoner of Azkaban',
    author: authors[13],
    genre: genres[3],
    price: 690,
    rentalPrice: 170,
    coverImage: getImage('new-book-31'),
    description: 'The third novel in the Harry Potter series. The book follows Harry Potter, a young wizard, in his third year at Hogwarts School of Witchcraft and Wizardry.',
    availability: 'in-stock',
  },
  {
    id: '40',
    title: 'Einstein: His Life and Universe',
    author: authors[14],
    genre: genres[5],
    price: 1050,
    rentalPrice: 250,
    coverImage: getImage('new-book-32'),
    description: 'A non-fiction book by Walter Isaacson, which was published in 2007. It is a biography of Albert Einstein.',
    availability: 'in-stock',
  },
  {
    id: '41',
    title: '21 Lessons for the 21st Century',
    author: authors[15],
    genre: genres[1],
    price: 800,
    rentalPrice: 190,
    coverImage: getImage('new-book-33'),
    description: 'A book by Yuval Noah Harari, which was published in 2018. It is a collection of essays about the present.',
    availability: 'in-stock',
  },
  {
    id: '42',
    title: 'Thinking, Fast and Slow',
    author: {id: '20', name: 'Daniel Kahneman'},
    genre: genres[6],
    price: 730,
    rentalPrice: 175,
    coverImage: getImage('new-book-34'),
    description: 'A 2011 book by psychologist Daniel Kahneman. The book\'s main thesis is a differentiation between two modes of thought: "System 1" is fast, instinctive and emotional; "System 2" is slower, more deliberative, and more logical.',
    availability: 'in-stock',
  },
  {
    id: '43',
    title: 'Rising Strong',
    author: authors[17],
    genre: genres[6],
    price: 700,
    rentalPrice: 170,
    coverImage: getImage('new-book-35'),
    description: 'A book by Brené Brown that explores what it takes to get back up from our falls, overcome our mistakes, and face hurt in a way that is both brave and vulnerable.',
    availability: 'in-stock',
  },
  {
    id: '44',
    title: 'The Great Gatsby',
    author: {id: '21', name: 'F. Scott Fitzgerald'},
    genre: genres[0],
    price: 360,
    rentalPrice: 90,
    coverImage: getImage('new-book-36'),
    description: 'A 1925 novel by American writer F. Scott Fitzgerald. Set in the Jazz Age on Long Island, the novel depicts narrator Nick Carraway\'s interactions with mysterious millionaire Jay Gatsby and Gatsby\'s obsession to reunite with his former lover, Daisy Buchanan.',
    availability: 'in-stock',
  },
  {
    id: '45',
    title: 'To Kill a Mockingbird',
    author: {id: '22', name: 'Harper Lee'},
    genre: genres[0],
    price: 410,
    rentalPrice: 105,
    coverImage: getImage('new-book-37'),
    description: 'A novel by Harper Lee published in 1960. Instantly successful, it is widely read in high schools and middle schools in the United States.',
    availability: 'out-of-stock',
  },
  {
    id: '46',
    title: 'Brave New World',
    author: {id: '23', name: 'Aldous Huxley'},
    genre: genres[2],
    price: 430,
    rentalPrice: 110,
    coverImage: getImage('new-book-38'),
    description: 'A dystopian novel by English author Aldous Huxley, written in 1931 and published in 1932.',
    availability: 'in-stock',
  },
  {
    id: '47',
    title: 'The Catcher in the Rye',
    author: {id: '24', name: 'J.D. Salinger'},
    genre: genres[0],
    price: 400,
    rentalPrice: 100,
    coverImage: getImage('new-book-39'),
    description: 'A novel by J. D. Salinger, partially published in serial form in 1945–1946 and as a novel in 1951.',
    availability: 'in-stock',
  },
  {
    id: '48',
    title: 'The Grapes of Wrath',
    author: {id: '25', name: 'John Steinbeck'},
    genre: genres[0],
    price: 520,
    rentalPrice: 125,
    coverImage: getImage('new-book-40'),
    description: 'An American realist novel written by John Steinbeck and published in 1939. The book won the National Book Award and Pulitzer Prize for fiction.',
    availability: 'in-stock',
  },
  {
    id: '49',
    title: 'The Psychology of Money',
    author: authors.find(a => a.name === 'Morgan Housel')!,
    genre: genres.find(g => g.name === 'Finance')!,
    price: 499,
    rentalPrice: 49,
    coverImage: getImage('psychology-of-money-cover'),
    description: 'Timeless lessons on wealth, greed, and happiness.',
    availability: 'in-stock',
  },
  {
    id: '50',
    title: 'The Alchemist',
    author: authors.find(a => a.name === 'Paulo Coelho')!,
    genre: genres.find(g => g.name === 'Fiction')!,
    price: 350,
    rentalPrice: 35,
    coverImage: getImage('alchemist-cover'),
    description: 'A fable about following your dream.',
    availability: 'in-stock',
  }
];

export const pdfs: Pdf[] = [];

export const upscPdfs: Pdf[] = [
  {
    id: "upsc-pdf-1",
    title: "Certificate Physical and Human Geography",
    author: "GC Leong",
    category: "UPSC",
    description: "A comprehensive text on physical and human geography.",
    coverImage: getImage("upsc-geo-leong"),
    downloadUrl: "#",
  },
  {
    id: "upsc-pdf-2",
    title: "Fundamentals of Physical Geography",
    author: "NCERT",
    category: "UPSC",
    description: "Class XI NCERT textbook covering fundamental geographical concepts.",
    coverImage: getImage("upsc-geo-ncert"),
    downloadUrl: "#",
  },
  {
    id: "upsc-pdf-3",
    title: "Indian Economy",
    author: "Ramesh Singh",
    category: "UPSC",
    description: "Seventh edition textbook for Civil Services Examinations.",
    coverImage: getImage("upsc-economy-ramesh"),
    downloadUrl: "#",
  },
  {
    id: "upsc-pdf-4",
    title: "India's Struggle For Independence",
    author: "Bipin Chandra",
    category: "UPSC",
    description: "Covers the history of India's freedom movement from 1857 to 1947.",
    coverImage: getImage("upsc-independence-struggle"),
    downloadUrl: "#",
  },
  {
    id: "upsc-pdf-5",
    title: "Introduction To The Constitution Of India",
    author: "Durga Das Basu",
    category: "UPSC",
    description: "A comprehensive guide to the Indian Constitution.",
    coverImage: getImage("upsc-constitution-basu"),
    downloadUrl: "#",
  },
  {
    id: "upsc-pdf-6",
    title: "Medieval India (NCERT)",
    author: "Satish Chandra",
    category: "UPSC",
    description: "NCERT textbook for Classes XI-XII on medieval Indian history.",
    coverImage: getImage("upsc-medieval-ncert"),
    downloadUrl: "#",
  },
  {
    id: "upsc-pdf-7",
    title: "History of Medieval India",
    author: "Satish Chandra",
    category: "UPSC",
    description: "Covers medieval Indian history between 800 and 1700.",
    coverImage: getImage("upsc-medieval-chandra"),
    downloadUrl: "#",
  },
  {
    id: "upsc-pdf-8",
    title: "Ethics, Integrity and Aptitude",
    author: "G Subba Rao & P N Roy Chowdhury",
    category: "UPSC",
    description: "Fourth edition textbook for the Civil Services Examination.",
    coverImage: getImage("upsc-ethics-aptitude"),
    downloadUrl: "#",
  },
  {
    id: "upsc-pdf-9",
    title: "History of Modern India",
    author: "Bipin Chandra",
    category: "UPSC",
    description: "Covers the modern period of Indian history.",
    coverImage: getImage("upsc-modern-india"),
    downloadUrl: "#",
  },
  {
    id: "upsc-pdf-10",
    title: "Indian Polity",
    author: "M. Laxmikanth",
    category: "UPSC",
    description: "Modules on political science, nation-states, and administration.",
    coverImage: getImage("upsc-polity-laxmikanth"),
    downloadUrl: "#",
  },
];

export const spaceAndAstronomyPdfs: Pdf[] = [
  {
    id: "space-pdf-1",
    title: "Awareness",
    author: "Anthony de Mello",
    category: "Space & Astronomy",
    description: "A spiritual guide to awareness, often related to cosmic consciousness.",
    coverImage: getImage("space-pdf-1"),
    downloadUrl: "#",
  },
  {
    id: "space-pdf-2",
    title: "Astrophysics For People In A Hurry",
    author: "Neil deGrasse Tyson",
    category: "Space & Astronomy",
    description: "A straightforward, easy-to-understand introduction to the laws that govern the universe.",
    coverImage: getImage("space-pdf-2"),
    downloadUrl: "#",
  },
  {
    id: "space-pdf-3",
    title: "Death by Black Hole And Other Cosmic Quandaries",
    author: "Neil deGrasse Tyson",
    category: "Space & Astronomy",
    description: "A collection of essays on the universe, from black holes to the search for extraterrestrial life.",
    coverImage: getImage("space-pdf-3"),
    downloadUrl: "#",
  },
  {
    id: "space-pdf-4",
    title: "Cosmos",
    author: "Carl Sagan",
    category: "Space & Astronomy",
    description: "The story of fifteen billion years of cosmic evolution, transforming complex scientific ideas into lyrical, accessible prose.",
    coverImage: getImage("space-pdf-4"),
    downloadUrl: "#",
  },
  {
    id: "space-pdf-5",
    title: "A Brief History of Time",
    author: "Stephen Hawking",
    category: "Space & Astronomy",
    description: "A landmark volume in science writing by one of the great minds of our time.",
    coverImage: getImage("space-pdf-5"),
    downloadUrl: "#",
  },
  {
    id: "space-pdf-6",
    title: "The Fabric of the Cosmos",
    author: "Brian Greene",
    category: "Space & Astronomy",
    description: "An exploration of the fundamental nature of space, time, and the universe.",
    coverImage: getImage("space-pdf-6"),
    downloadUrl: "#",
  },
  {
    id: "space-pdf-7",
    title: "The Milky Way Galaxy",
    author: "Various Authors",
    category: "Space & Astronomy",
    description: "A detailed look into our home galaxy, its structure, and its place in the universe.",
    coverImage: getImage("space-pdf-7"),
    downloadUrl: "#",

  },
  {
    id: "space-pdf-8",
    title: "The Right Stuff",
    author: "Tom Wolfe",
    category: "Space & Astronomy",
    description: "A chronicle of the early days of the U.S. space program and the lives of the first astronauts.",
    coverImage: getImage("space-pdf-8"),
    downloadUrl: "#",
  },
  {
    id: "space-pdf-9",
    title: "Welcome to the Universe",
    author: "Neil deGrasse Tyson, Michael A. Strauss, J. Richard Gott",
    category: "Space & Astronomy",
    description: "A personal guided tour of the cosmos by three of today’s leading astrophysicists.",
    coverImage: getImage("space-pdf-9"),
    downloadUrl: "#",
  },
];

export const selfDevelopmentPdfs: Pdf[] = [
    {
        id: "sd-pdf-1",
        title: "Alchemist",
        author: "Paulo Coelho",
        category: "Self Development",
        description: "A fable about following your dreams.",
        coverImage: getImage("sd-alchemist"),
        downloadUrl: "#",
    },
    {
        id: "sd-pdf-2",
        title: "Grit",
        author: "Angela Duckworth",
        category: "Self Development",
        description: "The power of passion and perseverance.",
        coverImage: getImage("sd-grit"),
        downloadUrl: "#",
    },
    {
        id: "sd-pdf-3",
        title: "Awareness",
        author: "Anthony de Mello",
        category: "Self Development",
        description: "The perils and opportunities of reality.",
        coverImage: getImage("sd-awareness"),
        downloadUrl: "#",
    },
    {
        id: "sd-pdf-4",
        title: "Atomic Habits",
        author: "James Clear",
        category: "Self Development",
        description: "An easy & proven way to build good habits & break bad ones.",
        coverImage: getImage("atomic-habits-cover"),
        downloadUrl: "#",
    },
    {
        id: "sd-pdf-5",
        title: "Awaken the Giant Within",
        author: "Anthony Robbins",
        category: "Self Development",
        description: "How to take immediate control of your mental, emotional, physical and financial destiny.",
        coverImage: getImage("sd-awaken-giant"),
        downloadUrl: "#",
    },
    {
        id: "sd-pdf-6",
        title: "Drive",
        author: "Daniel H. Pink",
        category: "Self Development",
        description: "The surprising truth about what motivates us.",
        coverImage: getImage("sd-drive"),
        downloadUrl: "#",
    },
    {
        id: "sd-pdf-7",
        title: "Emotional Intelligence",
        author: "Daniel Goleman",
        category: "Self Development",
        description: "Why it can matter more than IQ.",
        coverImage: getImage("sd-emotional-intelligence"),
        downloadUrl: "#",
    },
    {
        id: "sd-pdf-8",
        title: "How to Win Friends and Influence People",
        author: "Dale Carnegie",
        category: "Self Development",
        description: "The only book you need to lead you to success.",
        coverImage: getImage("sd-win-friends"),
        downloadUrl: "#",
    },
    {
        id: "sd-pdf-9",
        title: "Mindset",
        author: "Carol S. Dweck",
        category: "Self Development",
        description: "The new psychology of success.",
        coverImage: getImage("sd-mindset"),
        downloadUrl: "#",
    },
    {
        id: "sd-pdf-10",
        title: "The 7 Habits of Highly Effective People",
        author: "Stephen R. Covey",
        category: "Self Development",
        description: "Powerful lessons in personal change.",
        coverImage: getImage("sd-7-habits"),
        downloadUrl: "#",
    },
    {
        id: "sd-pdf-11",
        title: "The Miracle Morning",
        author: "Hal Elrod",
        category: "Self Development",
        description: "The not-so-obvious secret guaranteed to change your life before 8AM.",
        coverImage: getImage("sd-miracle-morning"),
        downloadUrl: "#",
    },
    {
        id: "sd-pdf-12",
        title: "The Power of Now",
        author: "Eckhart Tolle",
        category: "Self Development",
        description: "A guide to spiritual enlightenment.",
        coverImage: getImage("sd-power-of-now"),
        downloadUrl: "#",
    },
    {
        id: "sd-pdf-13",
        title: "The Untethered Soul",
        author: "Michael A. Singer",
        category: "Self Development",
        description: "The journey beyond yourself.",
        coverImage: getImage("sd-untethered-soul"),
        downloadUrl: "#",
    },
    {
        id: "sd-pdf-14",
        title: "The ONE Thing",
        author: "Gary Keller & Jay Papasan",
        category: "Self Development",
        description: "The surprisingly simple truth behind extraordinary results.",
        coverImage: getImage("sd-one-thing"),
        downloadUrl: "#",
    },
    {
        id: "sd-pdf-15",
        title: "The Subtle Art of Not Giving a F*ck",
        author: "Mark Manson",
        category: "Self Development",
        description: "A counterintuitive approach to living a good life.",
        coverImage: getImage("sd-subtle-art"),
        downloadUrl: "#",
    },
    {
        id: "sd-pdf-16",
        title: "Think And Grow Rich",
        author: "Napoleon Hill",
        category: "Self Development",
        description: "The landmark bestseller... now revised and updated for the 21st century.",
        coverImage: getImage("sd-think-grow-rich"),
        downloadUrl: "#",
    },
];

export const psychologyPdfs: Pdf[] = [
    {
        id: "psych-pdf-1",
        title: "Attachment in Psychotherapy",
        author: "David J. Wallin",
        category: "Psychology",
        description: "An exploration of attachment theory and its applications in therapy.",
        coverImage: getImage("psych-pdf-1"),
        downloadUrl: "#",
    },
    {
        id: "psych-pdf-2",
        title: "Thinking, Fast and Slow",
        author: "Daniel Kahneman",
        category: "Psychology",
        description: "A deep dive into the two systems that drive the way we think.",
        coverImage: getImage("psych-pdf-2"),
        downloadUrl: "#",
    },
    {
        id: "psych-pdf-3",
        title: "Flow: The Psychology of Optimal Experience",
        author: "Mihaly Csikszentmihalyi",
        category: "Psychology",
        description: "Investigates how to achieve a state of 'flow' and find genuine satisfaction.",
        coverImage: getImage("psych-pdf-3"),
        downloadUrl: "#",
    },
    {
        id: "psych-pdf-4",
        title: "Man’s Search for Meaning",
        author: "Viktor E. Frankl",
        category: "Psychology",
        description: "A psychiatrist's memoir of life in Nazi death camps and a lesson for spiritual survival.",
        coverImage: getImage("psych-pdf-4"),
        downloadUrl: "#",
    },
    {
        id: "psych-pdf-5",
        title: "Predictably Irrational",
        author: "Dan Ariely",
        category: "Psychology",
        description: "Challenges readers' assumptions about making decisions based on rational thought.",
        coverImage: getImage("psych-pdf-5"),
        downloadUrl: "#",
    },
    {
        id: "psych-pdf-6",
        title: "Quiet: The Power of Introverts in a World That Can’t Stop Talking",
        author: "Susan Cain",
        category: "Psychology",
        description: "A look at how introverts are undervalued in a world that prizes extroversion.",
        coverImage: getImage("psych-pdf-6"),
        downloadUrl: "#",
    },
    {
        id: "psych-pdf-7",
        title: "The Interpretation of Dreams",
        author: "Sigmund Freud",
        category: "Psychology",
        description: "The foundational work of psychoanalysis, exploring the unconscious mind through dreams.",
        coverImage: getImage("psych-pdf-7"),
        downloadUrl: "#",
    },
    {
        id: "psych-pdf-8",
        title: "The Power of Habit",
        author: "Charles Duhigg",
        category: "Psychology",
        description: "A scientific exploration of why habits exist and how they can be changed.",
        coverImage: getImage("psych-pdf-8"),
        downloadUrl: "#",
    },
    {
        id: "psych-pdf-9",
        title: "The Psychology Book: Big Ideas Simply Explained",
        author: "Nigel C. Benson et al.",
        category: "Psychology",
        description: "An accessible guide to the most important psychological concepts and theories.",
        coverImage: getImage("psych-pdf-9"),
        downloadUrl: "#",
    },
    {
        id: "psych-pdf-10",
        title: "Influence: The Psychology of Persuasion",
        author: "Robert B. Cialdini",
        category: "Psychology",
        description: "Explores the psychology of why people say 'yes' and how to apply these understandings.",
        coverImage: getImage("psych-pdf-10"),
        downloadUrl: "#",
    },
];
    
