
import type { Book, Author, Genre, CommunityPost, Pdf } from '@/lib/types';
import { PlaceHolderImages } from '@/lib/placeholder-images';

const getImage = (id: string) => {
  const image = PlaceHolderImages.find((img) => img.id === id);
  if (!image) {
    // Fallback to a default image if not found
    return { url: "https://picsum.photos/seed/default/400/600", hint: "image" };
  }
  return { url: image.imageUrl, hint: image.imageHint };
};

export const authors: Author[] = [
  { id: '1', name: 'Arundhati Roy' },
  { id: '2', name: 'Vikram Seth' },
  { id: '3', name: 'Amitav Ghosh' },
  { id: '4', name: 'Jhumpa Lahiri' },
  { id: '5', name: 'Frank Herbert' },
  { id: '6', name: 'Isaac Asimov' },
  { id: '7', name: 'George Orwell' },
  { id: '8', name: 'J.R.R. Tolkien' },
  { id: '9', name: 'Haruki Murakami' },
  { id: '10', name: 'Gabriel Garcia Marquez' },
  { id: '11', name: 'Jane Austen' },
  { id: '12', name: 'Agatha Christie' },
  { id: '13', name: 'Stephen King' },
  { id: '14', name: 'J.K. Rowling' },
  { id: '15', name: 'Walter Isaacson' },
  { id: '16', name: 'Yuval Noah Harari' },
  { id: '17', name: 'James Clear' },
  { id: '18', name: 'Brené Brown' },
];

export const genres: Genre[] = [
  { id: '1', name: 'Fiction' },
  { id: '2', name: 'Non-Fiction' },
  { id: '3', name: 'Science Fiction' },
  { id: '4', name: 'Fantasy' },
  { id: '5', name: 'Mystery' },
  { id: '6', name: 'Biography' },
  { id: '7', name: 'Self-Help' },
  { id: '8', name: 'Thriller' },
];

export const books: Book[] = [
  {
    id: '1',
    title: 'The God of Small Things',
    author: authors[0],
    genre: genres[0],
    price: 399,
    rentalPrice: 99,
    coverImage: getImage('book-cover-5'),
    description: 'A story about the childhood experiences of fraternal twins whose lives are destroyed by the "Love Laws" that lay down "who should be loved, and how. And how much."',
    availability: 'in-stock',
  },
  {
    id: '2',
    title: 'A Suitable Boy',
    author: authors[1],
    genre: genres[0],
    price: 899,
    rentalPrice: 199,
    coverImage: getImage('book-cover-6'),
    description: 'Set in a newly independent India, the novel follows the story of four families over a period of 18 months, and centers on Mrs. Rupa Mehra\'s efforts to arrange the marriage of her younger daughter, Lata, to a "suitable boy".',
    availability: 'in-stock',
  },
  {
    id: '3',
    title: 'The Glass Palace',
    author: authors[2],
    genre: genres[1],
    price: 599,
    coverImage: getImage('book-cover-7'),
    description: 'The novel is set in Burma, Bengal, India, and Malaya, spans a century from the fall of the Konbaung Dynasty in Mandalay, to the modern era.',
    availability: 'out-of-stock',
  },
  {
    id: '4',
    title: 'The Namesake',
    author: authors[3],
    genre: genres[0],
    price: 450,
    rentalPrice: 120,
    coverImage: getImage('book-cover-8'),
    description: 'The novel examines the intricacies of immigrant life, the conflicts of assimilation, and the tangled ties between generations.',
    availability: 'in-stock',
  },
  {
    id: '5',
    title: 'Sea of Poppies',
    author: authors[2],
    genre: genres[0],
    price: 650,
    rentalPrice: 150,
    coverImage: getImage('book-cover-5'),
    description: 'The first book of the Ibis trilogy, this novel is set in the first half of the 19th century, on the banks of the holy river Ganges, and on the ebb and tide of the Indian Ocean.',
    availability: 'in-stock',
  },
  {
    id: '6',
    title: 'The Ministry of Utmost Happiness',
    author: authors[0],
    genre: genres[0],
    price: 499,
    coverImage: getImage('book-cover-6'),
    description: 'The novel weaves together the stories of people from different backgrounds in India, exploring themes of love, identity, and politics.',
    availability: 'out-of-stock',
  },
  {
    id: '7',
    title: 'Dune',
    author: authors[4],
    genre: genres[2],
    price: 799,
    rentalPrice: 180,
    coverImage: getImage('book-cover-7'),
    description: 'A mythic and emotionally charged hero\'s journey, "Dune" tells the story of Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding.',
    availability: 'in-stock',
  },
  {
    id: '8',
    title: 'Foundation',
    author: authors[5],
    genre: genres[2],
    price: 550,
    rentalPrice: 130,
    coverImage: getImage('book-cover-8'),
    description: 'For twelve thousand years the Galactic Empire has ruled supreme. Now it is dying. But only Hari Seldon, creator of the revolutionary science of psychohistory, can see into the future.',
    availability: 'in-stock',
  },
  {
    id: '9',
    title: 'Nineteen Eighty-Four',
    author: authors[6],
    genre: genres[2],
    price: 450,
    rentalPrice: 110,
    coverImage: getImage('new-book-1'),
    description: 'A dystopian novel set in Airstrip One, a province of the superstate Oceania in a world of perpetual war, omnipresent government surveillance, and public manipulation.',
    availability: 'in-stock',
  },
  {
    id: '10',
    title: 'The Hobbit',
    author: authors[7],
    genre: genres[3],
    price: 600,
    rentalPrice: 140,
    coverImage: getImage('new-book-2'),
    description: 'The enchanting prequel to The Lord of the Rings, The Hobbit is the story of Bilbo Baggins, a quiet and unassuming hobbit whose life is turned upside down when he joins a company of dwarves on a quest to reclaim their stolen treasure.',
    availability: 'in-stock',
  },
  {
    id: '11',
    title: 'Norwegian Wood',
    author: authors[8],
    genre: genres[0],
    price: 520,
    rentalPrice: 125,
    coverImage: getImage('new-book-3'),
    description: 'A nostalgic story of loss and burgeoning sexuality. It is told from the first-person perspective of Toru Watanabe, who looks back on his days as a college student living in Tokyo.',
    availability: 'in-stock',
  },
  {
    id: '12',
    title: 'One Hundred Years of Solitude',
    author: authors[9],
    genre: genres[0],
    price: 580,
    rentalPrice: 135,
    coverImage: getImage('new-book-4'),
    description: 'The story of the Buendía family, and chronicles the irreconcilable conflict between the demand for solitude and the need for love—in a tragicomedy of the human condition.',
    availability: 'out-of-stock',
  },
  {
    id: '13',
    title: 'Pride and Prejudice',
    author: authors[10],
    genre: genres[0],
    price: 350,
    rentalPrice: 90,
    coverImage: getImage('new-book-5'),
    description: 'A romantic novel of manners written by Jane Austen. The novel follows the character development of Elizabeth Bennet, the dynamic protagonist of the book.',
    availability: 'in-stock',
  },
  {
    id: '14',
    title: 'And Then There Were None',
    author: authors[11],
    genre: genres[4],
    price: 480,
    rentalPrice: 115,
    coverImage: getImage('new-book-6'),
    description: 'Ten strangers are lured to a remote island off the coast of Devon. Upon arrival, it is discovered that their host is mysteriously absent.',
    availability: 'in-stock',
  },
  {
    id: '15',
    title: 'The Shining',
    author: authors[12],
    genre: genres[7],
    price: 620,
    rentalPrice: 155,
    coverImage: getImage('new-book-7'),
    description: 'The story of Jack Torrance, an aspiring writer and recovering alcoholic who accepts a position as the off-season caretaker of the isolated historic Overlook Hotel in the Colorado Rockies.',
    availability: 'in-stock',
  },
  {
    id: '16',
    title: 'Harry Potter and the Sorcerer\'s Stone',
    author: authors[13],
    genre: genres[3],
    price: 650,
    rentalPrice: 160,
    coverImage: getImage('new-book-8'),
    description: 'The first novel in the Harry Potter series, it follows Harry Potter, a young wizard who discovers his magical heritage on his eleventh birthday, when he receives a letter of acceptance to Hogwarts School of Witchcraft and Wizardry.',
    availability: 'in-stock',
  },
  {
    id: '17',
    title: 'Steve Jobs',
    author: authors[14],
    genre: genres[5],
    price: 950,
    rentalPrice: 220,
    coverImage: getImage('new-book-9'),
    description: 'The authorized self-titled biography of Steve Jobs. The book was written at the request of Jobs by Walter Isaacson, a former executive at CNN and TIME.',
    availability: 'in-stock',
  },
  {
    id: '18',
    title: 'Sapiens: A Brief History of Humankind',
    author: authors[15],
    genre: genres[1],
    price: 750,
    rentalPrice: 180,
    coverImage: getImage('new-book-10'),
    description: 'A book by Yuval Noah Harari, first published in Hebrew in Israel in 2011 based on a series of lectures Harari taught at The Hebrew University of Jerusalem.',
    availability: 'in-stock',
  },
  {
    id: '19',
    title: 'Atomic Habits',
    author: authors[16],
    genre: genres[6],
    price: 700,
    rentalPrice: 170,
    coverImage: getImage('new-book-11'),
    description: 'An easy and proven way to build good habits and break bad ones. It offers a framework for improving every day.',
    availability: 'out-of-stock',
  },
  {
    id: '20',
    title: 'Daring Greatly',
    author: authors[17],
    genre: genres[6],
    price: 680,
    rentalPrice: 165,
    coverImage: getImage('new-book-12'),
    description: 'A book by Brené Brown that discusses the power of vulnerability, courage, worthiness, and shame.',
    availability: 'in-stock',
  },
  {
    id: '21',
    title: 'The Lord of the Rings',
    author: authors[7],
    genre: genres[3],
    price: 1200,
    rentalPrice: 250,
    coverImage: getImage('new-book-13'),
    description: 'An epic high-fantasy novel. The story began as a sequel to Tolkien\'s 1937 fantasy novel The Hobbit, but eventually developed into a much larger work.',
    availability: 'in-stock',
  },
  {
    id: '22',
    title: 'Kafka on the Shore',
    author: authors[8],
    genre: genres[0],
    price: 560,
    rentalPrice: 130,
    coverImage: getImage('new-book-14'),
    description: 'A 2002 novel by Japanese author Haruki Murakami. Its 2005 English translation was among "The 10 Best Books of 2005" from The New York Times.',
    availability: 'in-stock',
  },
  {
    id: '23',
    title: 'Love in the Time of Cholera',
    author: authors[9],
    genre: genres[0],
    price: 540,
    rentalPrice: 125,
    coverImage: getImage('new-book-15'),
    description: 'A novel that tells the story of Florentino Ariza and his love for Fermina Daza.',
    availability: 'in-stock',
  },
  {
    id: '24',
    title: 'Sense and Sensibility',
    author: authors[10],
    genre: genres[0],
    price: 380,
    rentalPrice: 95,
    coverImage: getImage('new-book-16'),
    description: 'A novel by Jane Austen, published in 1811. It was published anonymously; "By a Lady" appeared on the title page where the author\'s name might have been.',
    availability: 'out-of-stock',
  },
  {
    id: '25',
    title: 'Murder on the Orient Express',
    author: authors[11],
    genre: genres[4],
    price: 490,
    rentalPrice: 120,
    coverImage: getImage('new-book-17'),
    description: 'A detective novel by British writer Agatha Christie, featuring the Belgian detective Hercule Poirot.',
    availability: 'in-stock',
  },
  {
    id: '26',
    title: 'It',
    author: authors[12],
    genre: genres[7],
    price: 720,
    rentalPrice: 175,
    coverImage: getImage('new-book-18'),
    description: 'A 1986 horror novel by American author Stephen King. It was his 22nd book and his 17th novel written under his own name.',
    availability: 'in-stock',
  },
  {
    id: '27',
    title: 'Harry Potter and the Chamber of Secrets',
    author: authors[13],
    genre: genres[3],
    price: 670,
    rentalPrice: 165,
    coverImage: getImage('new-book-19'),
    description: 'The second novel in the Harry Potter series. The plot follows Harry\'s second year at Hogwarts School of Witchcraft and Wizardry.',
    availability: 'in-stock',
  },
  {
    id: '28',
    title: 'Leonardo da Vinci',
    author: authors[14],
    genre: genres[5],
    price: 1100,
    rentalPrice: 240,
    coverImage: getImage('new-book-20'),
    description: 'A biography of Leonardo da Vinci by Walter Isaacson. It is based on Leonardo\'s notebooks and new discoveries about his life and work.',
    availability: 'in-stock',
  },
  {
    id: '29',
    title: 'Homo Deus: A Brief History of Tomorrow',
    author: authors[15],
    genre: genres[1],
    price: 780,
    rentalPrice: 185,
    coverImage: getImage('new-book-21'),
    description: 'A book written by Israeli author Yuval Noah Harari, professor at the Hebrew University in Jerusalem. The book was first published in Hebrew in 2015.',
    availability: 'in-stock',
  },
  {
    id: '30',
    title: 'The Power of Habit',
    author: {id: '19', name: 'Charles Duhigg'},
    genre: genres[6],
    price: 710,
    rentalPrice: 170,
    coverImage: getImage('new-book-22'),
    description: 'A book by Charles Duhigg, a New York Times reporter, published in February 2012 by Random House.',
    availability: 'in-stock',
  },
  {
    id: '31',
    title: 'The Gifts of Imperfection',
    author: authors[17],
    genre: genres[6],
    price: 690,
    rentalPrice: 168,
    coverImage: getImage('new-book-23'),
    description: 'A New York Times bestseller by Brené Brown that has been helping readers to embrace a more authentic and wholehearted life.',
    availability: 'out-of-stock',
  },
  {
    id: '32',
    title: 'Animal Farm',
    author: authors[6],
    genre: genres[2],
    price: 320,
    rentalPrice: 80,
    coverImage: getImage('new-book-24'),
    description: 'An allegorical novella by George Orwell, first published in England on 17 August 1945.',
    availability: 'in-stock',
  },
  {
    id: '33',
    title: 'The Silmarillion',
    author: authors[7],
    genre: genres[3],
    price: 850,
    rentalPrice: 200,
    coverImage: getImage('new-book-25'),
    description: 'A collection of mythopoeic works by English writer J. R. R. Tolkien, edited and published posthumously by his son, Christopher Tolkien, in 1977.',
    availability: 'in-stock',
  },
  {
    id: '34',
    title: '1Q84',
    author: authors[8],
    genre: genres[0],
    price: 980,
    rentalPrice: 220,
    coverImage: getImage('new-book-26'),
    description: 'A dystopian novel written by Japanese writer Haruki Murakami, first published in three volumes in Japan in 2009–10.',
    availability: 'in-stock',
  },
  {
    id: '35',
    title: 'Chronicle of a Death Foretold',
    author: authors[9],
    genre: genres[0],
    price: 420,
    rentalPrice: 100,
    coverImage: getImage('new-book-27'),
    description: 'A novella by Gabriel García Márquez, published in 1981. It tells, in the form of a pseudo-journalistic reconstruction, the story of the murder of Santiago Nasar by the two Vicario brothers.',
    availability: 'in-stock',
  },
  {
    id: '36',
    title: 'Emma',
    author: authors[10],
    genre: genres[0],
    price: 400,
    rentalPrice: 100,
    coverImage: getImage('new-book-28'),
    description: 'A novel about youthful hubris and romantic misunderstandings, written by Jane Austen. It is set in the fictional country village of Highbury and the surrounding estates of Hartfield, Randalls and Donwell Abbey.',
    availability: 'in-stock',
  },
  {
    id: '37',
    title: 'The Murder of Roger Ackroyd',
    author: authors[11],
    genre: genres[4],
    price: 500,
    rentalPrice: 125,
    coverImage: getImage('new-book-29'),
    description: 'A work of detective fiction by British writer Agatha Christie, first published in June 1926 in the United Kingdom by William Collins, Sons.',
    availability: 'out-of-stock',
  },
  {
    id: '38',
    title: 'The Stand',
    author: authors[12],
    genre: genres[7],
    price: 880,
    rentalPrice: 210,
    coverImage: getImage('new-book-30'),
    description: 'A post-apocalyptic dark fantasy novel written by American author Stephen King and first published in 1978 by Doubleday.',
    availability: 'in-stock',
  },
  {
    id: '39',
    title: 'Harry Potter and the Prisoner of Azkaban',
    author: authors[13],
    genre: genres[3],
    price: 690,
    rentalPrice: 170,
    coverImage: getImage('new-book-31'),
    description: 'The third novel in the Harry Potter series. The book follows Harry Potter, a young wizard, in his third year at Hogwarts School of Witchcraft and Wizardry.',
    availability: 'in-stock',
  },
  {
    id: '40',
    title: 'Einstein: His Life and Universe',
    author: authors[14],
    genre: genres[5],
    price: 1050,
    rentalPrice: 250,
    coverImage: getImage('new-book-32'),
    description: 'A non-fiction book by Walter Isaacson, which was published in 2007. It is a biography of Albert Einstein.',
    availability: 'in-stock',
  },
  {
    id: '41',
    title: '21 Lessons for the 21st Century',
    author: authors[15],
    genre: genres[1],
    price: 800,
    rentalPrice: 190,
    coverImage: getImage('new-book-33'),
    description: 'A book by Yuval Noah Harari, which was published in 2018. It is a collection of essays about the present.',
    availability: 'in-stock',
  },
  {
    id: '42',
    title: 'Thinking, Fast and Slow',
    author: {id: '20', name: 'Daniel Kahneman'},
    genre: genres[6],
    price: 730,
    rentalPrice: 175,
    coverImage: getImage('new-book-34'),
    description: 'A 2011 book by psychologist Daniel Kahneman. The book\'s main thesis is a differentiation between two modes of thought: "System 1" is fast, instinctive and emotional; "System 2" is slower, more deliberative, and more logical.',
    availability: 'in-stock',
  },
  {
    id: '43',
    title: 'Rising Strong',
    author: authors[17],
    genre: genres[6],
    price: 700,
    rentalPrice: 170,
    coverImage: getImage('new-book-35'),
    description: 'A book by Brené Brown that explores what it takes to get back up from our falls, overcome our mistakes, and face hurt in a way that is both brave and vulnerable.',
    availability: 'in-stock',
  },
  {
    id: '44',
    title: 'The Great Gatsby',
    author: {id: '21', name: 'F. Scott Fitzgerald'},
    genre: genres[0],
    price: 360,
    rentalPrice: 90,
    coverImage: getImage('new-book-36'),
    description: 'A 1925 novel by American writer F. Scott Fitzgerald. Set in the Jazz Age on Long Island, the novel depicts narrator Nick Carraway\'s interactions with mysterious millionaire Jay Gatsby and Gatsby\'s obsession to reunite with his former lover, Daisy Buchanan.',
    availability: 'in-stock',
  },
  {
    id: '45',
    title: 'To Kill a Mockingbird',
    author: {id: '22', name: 'Harper Lee'},
    genre: genres[0],
    price: 410,
    rentalPrice: 105,
    coverImage: getImage('new-book-37'),
    description: 'A novel by Harper Lee published in 1960. Instantly successful, it is widely read in high schools and middle schools in the United States.',
    availability: 'out-of-stock',
  },
  {
    id: '46',
    title: 'Brave New World',
    author: {id: '23', name: 'Aldous Huxley'},
    genre: genres[2],
    price: 430,
    rentalPrice: 110,
    coverImage: getImage('new-book-38'),
    description: 'A dystopian novel by English author Aldous Huxley, written in 1931 and published in 1932.',
    availability: 'in-stock',
  },
  {
    id: '47',
    title: 'The Catcher in the Rye',
    author: {id: '24', name: 'J.D. Salinger'},
    genre: genres[0],
    price: 400,
    rentalPrice: 100,
    coverImage: getImage('new-book-39'),
    description: 'A novel by J. D. Salinger, partially published in serial form in 1945–1946 and as a novel in 1951.',
    availability: 'in-stock',
  },
  {
    id: '48',
    title: 'The Grapes of Wrath',
    author: {id: '25', name: 'John Steinbeck'},
    genre: genres[0],
    price: 520,
    rentalPrice: 125,
    coverImage: getImage('new-book-40'),
    description: 'An American realist novel written by John Steinbeck and published in 1939. The book won the National Book Award and Pulitzer Prize for fiction.',
    availability: 'in-stock',
  }
];

export const pdfs: Pdf[] = [
  // Classic Literature
  { id: 'pdf-cl1', title: 'The Great Gatsby', author: 'F. Scott Fitzgerald', category: 'Classic Literature', description: 'A novel about the American dream, decadence, and the roaring twenties.', coverImage: getImage('pdf-cover-1'), downloadUrl: 'https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf' },
  { id: 'pdf-cl2', title: 'To Kill a Mockingbird', author: 'Harper Lee', category: 'Classic Literature', description: 'A novel about the seriousness of racial inequality in the American South.', coverImage: getImage('pdf-cl2-cover'), downloadUrl: 'https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf' },
  { id: 'pdf-cl3', title: '1984', author: 'George Orwell', category: 'Classic Literature', description: 'A dystopian novel set in a totalitarian society under constant surveillance.', coverImage: getImage('pdf-cl3-cover'), downloadUrl: 'https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf' },
  { id: 'pdf-cl4', title: 'Moby Dick', author: 'Herman Melville', category: 'Classic Literature', description: 'The saga of Captain Ahab and his relentless pursuit of the great white whale.', coverImage: getImage('pdf-cl4-cover'), downloadUrl: 'https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf' },
  { id: 'pdf-cl5', title: 'The Catcher in the Rye', author: 'J.D. Salinger', category: 'Classic Literature', description: 'A story about teenage angst and alienation.', coverImage: getImage('pdf-cl5-cover'), downloadUrl: 'https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf' },
  { id: 'pdf-cl6', title: 'Brave New World', author: 'Aldous Huxley', category: 'Classic Literature', description: 'A dystopian novel about a future society driven by technology and science.', coverImage: getImage('pdf-cl6-cover'), downloadUrl: 'https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf' },
  { id: 'pdf-cl7', title: 'The Picture of Dorian Gray', author: 'Oscar Wilde', category: 'Classic Literature', description: 'A novel about a man who remains young while his portrait ages.', coverImage: getImage('pdf-cl7-cover'), downloadUrl: 'https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf' },
  { id: 'pdf-cl8', title: 'Frankenstein', author: 'Mary Shelley', category: 'Classic Literature', description: 'A scientist creates a sentient creature in an unorthodox scientific experiment.', coverImage: getImage('pdf-cl8-cover'), downloadUrl: 'https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf' },
  { id: 'pdf-cl9', title: 'Don Quixote', author: 'Miguel de Cervantes', category: 'Classic Literature', description: 'A Spanish nobleman who reads so many chivalric romances that he loses his sanity.', coverImage: getImage('pdf-cl9-cover'), downloadUrl: 'https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf' },
  { id: 'pdf-cl10', title: 'War and Peace', author: 'Leo Tolstoy', category: 'Classic Literature', description: 'A novel that chronicles the history of the French invasion of Russia.', coverImage: getImage('pdf-cl10-cover'), downloadUrl: 'https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf' },

  // Classic Romance
  { id: 'pdf-cr1', title: 'Pride and Prejudice', author: 'Jane Austen', category: 'Classic Romance', description: 'A romantic novel of manners that satirizes the societal expectations of women.', coverImage: getImage('pdf-cover-2'), downloadUrl: 'https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf' },
  { id: 'pdf-cr2', title: 'Jane Eyre', author: 'Charlotte Brontë', category: 'Classic Romance', description: 'The story of a young, orphaned governess who falls in love with her employer.', coverImage: getImage('pdf-cr2-cover'), downloadUrl: 'https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf' },
  { id: 'pdf-cr3', title: 'Wuthering Heights', author: 'Emily Brontë', category: 'Classic Romance', description: 'A tale of passionate, yet thwarted, love between Catherine Earnshaw and Heathcliff.', coverImage: getImage('pdf-cr3-cover'), downloadUrl: 'https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf' },
  { id: 'pdf-cr4', title: 'Sense and Sensibility', author: 'Jane Austen', category: 'Classic Romance', description: 'The story of two sisters, Elinor and Marianne Dashwood, and their different approaches to love.', coverImage: getImage('pdf-cr4-cover'), downloadUrl: 'https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf' },
  { id: 'pdf-cr5', title: 'Anna Karenina', author: 'Leo Tolstoy', category: 'Classic Romance', description: 'A tragic story of a married aristocrat and her affair with the affluent Count Vronsky.', coverImage: getImage('pdf-cr5-cover'), downloadUrl: 'https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf' },
  { id: 'pdf-cr6', title: 'Gone with the Wind', author: 'Margaret Mitchell', category: 'Classic Romance', description: 'A sweeping romantic story set in the American South during the Civil War.', coverImage: getImage('pdf-cr6-cover'), downloadUrl: 'https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf' },
  { id: 'pdf-cr7', title: 'The Age of Innocence', author: 'Edith Wharton', category: 'Classic Romance', description: 'A tale of a young lawyer and his fiancée in the rigid high society of 1870s New York.', coverImage: getImage('pdf-cr7-cover'), downloadUrl: 'https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf' },
  { id: 'pdf-cr8', title: 'Romeo and Juliet', author: 'William Shakespeare', category: 'Classic Romance', description: 'A tragedy about two young star-crossed lovers whose deaths ultimately reconcile their feuding families.', coverImage: getImage('pdf-cr8-cover'), downloadUrl: 'https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf' },
  { id: 'pdf-cr9', title: 'Persuasion', author: 'Jane Austen', category: 'Classic Romance', description: 'Austen\'s last completed novel, a story of second chances.', coverImage: getImage('pdf-cr9-cover'), downloadUrl: 'https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf' },
  { id: 'pdf-cr10', title: 'Emma', author: 'Jane Austen', category: 'Classic Romance', description: 'A novel about youthful hubris and the perils of misconstrued romance.', coverImage: getImage('pdf-cr10-cover'), downloadUrl: 'https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf' },

  // Strategy & Philosophy
  { id: 'pdf-sp1', title: 'The Art of War', author: 'Sun Tzu', category: 'Strategy & Philosophy', description: 'An ancient Chinese military treatise applicable to many fields.', coverImage: getImage('pdf-cover-3'), downloadUrl: 'https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf' },
  { id: 'pdf-sp2', title: 'Meditations', author: 'Marcus Aurelius', category: 'Strategy & Philosophy', description: 'A series of personal writings by the Roman Emperor, exploring Stoic philosophy.', coverImage: getImage('pdf-sp2-cover'), downloadUrl: 'https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf' },
  { id: 'pdf-sp3', title: 'The Prince', author: 'Niccolò Machiavelli', category: 'Strategy & Philosophy', description: 'A 16th-century political treatise on how a prince should rule.', coverImage: getImage('pdf-sp3-cover'), downloadUrl: 'https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf' },
  { id: 'pdf-sp4', title: 'The Republic', author: 'Plato', category: 'Strategy & Philosophy', description: 'A Socratic dialogue concerning justice, the order and character of the just city-state and the just man.', coverImage: getImage('pdf-sp4-cover'), downloadUrl: 'https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf' },
  { id: 'pdf-sp5', title: 'Beyond Good and Evil', author: 'Friedrich Nietzsche', category: 'Strategy & Philosophy', description: 'A critique of past philosophers who, he argues, lacked critical sense.', coverImage: getImage('pdf-sp5-cover'), downloadUrl: 'https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf' },
  { id: 'pdf-sp6', title: 'The Analects', author: 'Confucius', category: 'Strategy & Philosophy', description: 'A collection of sayings and ideas attributed to the Chinese philosopher Confucius.', coverImage: getImage('pdf-sp6-cover'), downloadUrl: 'https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf' },
  { id: 'pdf-sp7', title: 'Discourse on Method', author: 'René Descartes', category: 'Strategy & Philosophy', description: 'An autobiographical treatise about the search for truth in the sciences.', coverImage: getImage('pdf-sp7-cover'), downloadUrl: 'https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf' },
  { id: 'pdf-sp8', title: 'The Social Contract', author: 'Jean-Jacques Rousseau', category: 'Strategy & Philosophy', description: 'A work on political philosophy that discusses the best way to establish a political community.', coverImage: getImage('pdf-sp8-cover'), downloadUrl: 'https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf' },
  { id: 'pdf-sp9', title: 'On Liberty', author: 'John Stuart Mill', category: 'Strategy & Philosophy', description: 'A philosophical work that supports Mill\'s ethical system of utilitarianism.', coverImage: getImage('pdf-sp9-cover'), downloadUrl: 'https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf' },
  { id: 'pdf-sp10', title: 'Tao Te Ching', author: 'Laozi', category: 'Strategy & Philosophy', description: 'A fundamental text for both philosophical and religious Taoism.', coverImage: getImage('pdf-sp10-cover'), downloadUrl: 'https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf' },
  
  // Historical Fiction
  { id: 'pdf-hf1', title: 'A Tale of Two Cities', author: 'Charles Dickens', category: 'Historical Fiction', description: 'A historical novel set in London and Paris before and during the French Revolution.', coverImage: getImage('pdf-cover-4'), downloadUrl: 'https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf' },
  { id: 'pdf-hf2', title: 'The Name of the Rose', author: 'Umberto Eco', category: 'Historical Fiction', description: 'A historical murder mystery set in an Italian monastery in the year 1327.', coverImage: getImage('pdf-hf2-cover'), downloadUrl: 'https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf' },
  { id: 'pdf-hf3', title: 'I, Claudius', author: 'Robert Graves', category: 'Historical Fiction', description: 'An autobiography of the Roman Emperor Claudius.', coverImage: getImage('pdf-hf3-cover'), downloadUrl: 'https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf' },
  { id: 'pdf-hf4', title: 'Wolf Hall', author: 'Hilary Mantel', category: 'Historical Fiction', description: 'A fictionalised biography documenting the rapid rise to power of Thomas Cromwell.', coverImage: getImage('pdf-hf4-cover'), downloadUrl: 'https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf' },
  { id: 'pdf-hf5', title: 'The Pillars of the Earth', author: 'Ken Follett', category: 'Historical Fiction', description: 'A historical novel about the building of a cathedral in the fictional town of Kingsbridge, England.', coverImage: getImage('pdf-hf5-cover'), downloadUrl: 'https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf' },
  { id: 'pdf-hf6', title: 'The Three Musketeers', author: 'Alexandre Dumas', category: 'Historical Fiction', description: 'A historical adventure novel set in 17th-century France.', coverImage: getImage('pdf-hf6-cover'), downloadUrl: 'https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf' },
  { id: 'pdf-hf7', title: 'The Count of Monte Cristo', author: 'Alexandre Dumas', category: 'Historical Fiction', description: 'An adventure novel that takes place in France, Italy, and islands in the Mediterranean during 1815–1839.', coverImage: getImage('pdf-hf7-cover'), downloadUrl: 'https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf' },
  { id: 'pdf-hf8', title: 'Ben-Hur: A Tale of the Christ', author: 'Lew Wallace', category: 'Historical Fiction', description: 'A novel about a fictional Jewish prince from Jerusalem who is enslaved by the Romans.', coverImage: getImage('pdf-hf8-cover'), downloadUrl: 'https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf' },
  { id: 'pdf-hf9', title: 'The Scarlet Pimpernel', author: 'Baroness Orczy', category: 'Historical Fiction', description: 'A classic adventure novel set during the French Revolution.', coverImage: getImage('pdf-hf9-cover'), downloadUrl: 'https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf' },
  { id: 'pdf-hf10', title: 'Ivanhoe', author: 'Sir Walter Scott', category: 'Historical Fiction', description: 'A historical novel set in 12th-century England, an example of the historical romance genre.', coverImage: getImage('pdf-hf10-cover'), downloadUrl: 'https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf' },
];


export const communityPosts: CommunityPost[] = [
  {
    id: '1',
    title: 'What is everyone reading this week?',
    author: {
      name: 'Priya Sharma',
      avatar: getImage('user-avatar-1'),
    },
    content: 'Just finished "The God of Small Things" and it was breathtaking. Looking for recommendations for my next read! Preferably something in the non-fiction space about Hyderabad.',
    timestamp: '2 hours ago',
    replies: 5,
  },
  {
    id: '2',
    title: 'Book club meeting for "A Suitable Boy" - Discussion',
    author: {
      name: 'Rohan Reddy',
      avatar: getImage('user-avatar-2'),
    },
    content: 'Let\'s discuss the themes and characters of Vikram Seth\'s masterpiece. What did you all think of Lata\'s final choice? We will be meeting at Lamakaan this Saturday at 5 PM.',
    timestamp: '1 day ago',
    replies: 12,
  },
  {
    id: '3',
    title: 'Best places to read in Hyderabad?',
    author: {
      name: 'Anika Singh',
      avatar: getImage('user-avatar-3'),
    },
    content: 'Looking for some quiet cafes or parks in Hyderabad to spend an afternoon reading. Any hidden gems I should know about? I\'ve tried all the usual spots.',
    timestamp: '3 days ago',
    replies: 8,
  },
];
